default:
  outputs:
    dev:
      dbname: "{{ env_var('DESTINATION__POSTGRES__CREDENTIALS__DATABASE', 'your_database') }}"
      host: "{{ env_var('DESTINATION__POSTGRES__CREDENTIALS__HOST', 'your_db_host') }}"
      pass: "{{ env_var('DESTINATION__POSTGRES__CREDENTIALS__PASSWORD', 'your_db_pass') }}"
      port: 5432
      schema: dagster_dbt
      threads: 1
      type: postgres
      user: "{{ env_var('DESTINATION__POSTGRES__CREDENTIALS__USERNAME', 'your_db_user') }}"
  target: dev
